### ISSUE TITLE
Failed to activate the serenade package

### ISSUE THREAD

**Issue by metanoiex** [serenadeai/atom#1]
[Enter steps to reproduce:]

1. Opened atom, error thrown.
**Atom**: 1.39.0 x64 (Note: Error was only thrown after last update, and was thrown immediately upon restarting post-update)
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [serenade](https://github.com/serenadeai/atom) package 1.0.2

### Stack Trace

Failed to activate the serenade package

```
At EBUSY: resource busy or locked, unlink 'C:\Users\Admin\.serenade\jdk\jdk-11.0.2\lib\modules'

Error: EBUSY: resource busy or locked, unlink 'C:\Users\Admin\.serenade\jdk\jdk-11.0.2\lib\modules'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at /packages/serenade/build/extension.js:1:90887)
    at /packages/serenade/build/extension.js:1:91284
    at Array.forEach (<anonymous>)
    at /packages/serenade/build/extension.js:1:91264
    at /packages/serenade/build/extension.js:1:91410)
    at /packages/serenade/build/extension.js:1:90873)
    at /packages/serenade/build/extension.js:1:91284
    at Array.forEach (<anonymous>)
    at /packages/serenade/build/extension.js:1:91264
    at /packages/serenade/build/extension.js:1:91410)
    at /packages/serenade/build/extension.js:1:90873)
    at /packages/serenade/build/extension.js:1:91284
    at Array.forEach (<anonymous>)
    at /packages/serenade/build/extension.js:1:91264
    at /packages/serenade/build/extension.js:1:91410)
    at /packages/serenade/build/extension.js:1:90873)
    at e.default.downloadAndDecompress (/packages/serenade/build/extension.js:1:6677)
    at e.default.installJdk (/packages/serenade/build/extension.js:1:7760)
    at e.default.installAndRun (/packages/serenade/build/extension.js:1:7117)
    at e.default.run (/packages/serenade/build/extension.js:1:87037)
    at e.default.initialize (/packages/serenade/build/extension.js:1:59153)
    at e.default.activate (/packages/serenade/build/extension.js:1:58415)
    at Object.e.activate (/packages/serenade/build/extension.js:1:58140)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3541949)
    at measure (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3541361)
    at Package.measure (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3538971)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3541221)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3541164)
```
### Non-Core Packages

```
atom-clock 0.1.17 
atom-discord 2.0.2 
atom-live-server 2.3.0 
atom-mysql-snippets 0.3.1 
atom-prettify 0.1.3 
auto-save-on-idle 1.2.1 
better-python-snippets 1.0.0 
bracket-colorizer 1.4.0 
css-color-name 0.4.0 
css-spy 0.6.0 
file-icons 2.1.33 
flatify-ui 0.2.0 
highlight-colors 0.5.3 
html-head-snippets 0.2.0 
html-presets 1.1.2 
html-template-generator 0.3.0 
html-to-css 0.2.2 
ide-css 0.3.2 
ide-html 0.5.0 
ide-python 1.4.1 
language-arduino 0.4.3 
language-renpy 2.5.0 
language-sql-mysql 0.3.1 
moonlight 0.11.0 
one-dark-nova-syntax 1.7.0 
pseudo-synthesizer 0.5.1 
script 3.18.1 
scroll-color 0.3.0 
serenade 1.0.2 
sermon 0.1.6 
sourcerer 2.0.0 
spotify-neon 1.2.3 
teletype 0.13.4 
the-bespoke-pixel-ui 1.0.5 
todo-show 2.3.2 
weboutline 0.6.1 
```

**Comment by tmacwill** [comment]
Thanks for downloading Serenade and reporting this issue with detailed repro steps! I just did some testing and confirmed this is due to an issue in v0.1.3 with killing the Serenade process on Windows. 

To get back up and running, follow these steps:

1. Quit Atom.
2. In your tray, you should see the Serenade icon (a gold S on a black circle). Right-click that icon, and select "Quit Serenade".
3. Make sure you have the latest version of Serenade for Atom installed, which should be 1.0.2.
4. Re-open Atom, and the plugin should install again.

Let me know if that doesn't work!

**Comment by metanoiex** [comment]
Edit: Nevermind, reinstalled the atom plugin and found what you were talking about. It threw another error, but that one's already been reported, and it looks like Serenade is installing itself again.
Thanks for your help!

**Comment by tmacwill** [comment]
Glad it's working now! Don't hesitate to reach out if you run into any other issues or have any questions!
